# Generated by Django 4.2.2 on 2024-04-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdata',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='teacherdata',
            name='div',
        ),
        migrations.RemoveField(
            model_name='teacherdata',
            name='year',
        ),
    ]
