# Generated by Django 4.2.2 on 2024-04-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendapp', '0005_studattendence_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
