# Generated by Django 4.2.2 on 2024-04-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendapp', '0007_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='studattendence',
            name='day',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='studattendence',
            name='div',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='studattendence',
            name='starttime',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='studattendence',
            name='year',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
